race_sequence = [(-360, "s", "chime.wav"),
                 (-358, "s", "six_minutes.wav"),
                 (-357, "s", "to start.wav"),
                 (-180, "s", "chime.wav"),
                 (-178, "s", "three_minutes.wav"),
                 (-177, "s", "to_start.wav"),
                 (-60, "s", "chime.wav"),
                 (-58, "s", "one_minute.wav"),
                 (-57, "s", "to_start.wav"),
                 (-30, "s", "thirty_seconds.wav"),
                 (-10, "s", "ten.wav"),
                 (-9, "s", "nine.wav"),
                 (-8, "s", "eight.wav"),
                 (-7, "s", "seven.wav"),
                 (-6, "s", "six.wav"),
                 (-5, "s", "five.wav"),
                 (-4, "s", "four.wav"),
                 (-3, "s", "three.wav"),
                 (-2, "s", "two.wav"),
                 (-1, "s", "one.wav"),
                 (0, "s", "go.wav"),
                 (-60, "f", "chime.wav"),
                 (-58, "f", "one_minute.wav"),
                 (-57, "f", "to_finish.wav"),
                 (-30, "f", "thirty_seconds.wav"),
                 (-10, "f", "ten.wav"),
                 (-9, "f", "nine.wav"),
                 (-8, "f", "eight.wav"),
                 (-7, "f", "seven.wav"),
                 (-6, "f", "six.wav"),
                 (-5, "f", "five.wav"),
                 (-4, "f", "four.wav"),
                 (-3, "f", "three.wav"),
                 (-2, "f", "two.wav"),
                 (-1, "f", "one.wav"),
                 (0, "f", "finish.wav"),
                 ]